name: Update Token List

on:
  push:
    branches:
      - main 
      - feat/workflow

jobs:
  update-token-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Run script to generate tokenList.json
        run: node ./scripts/fromTokenDirToTokenList.js

      - name: Commit and push if changed
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add ./tokenList.json
          git commit -m "Update tokenList.json" -a || exit 0  # Exit gracefully if no changes
          git push
