name: Update Token List

on:
  push:
    branches:
      - main 
permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none
  
jobs:
  update-token-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Run merge script
        run: yarn merge ${{ secrets.TRUSTLINES_PRIVATE_KEY }}

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update tokenList.json"
          commit_options: '-a'  # Include changes to all tracked files
          branch: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
