name: Verify new Tokens

on:
  pull_request:
    branches:
      - main   
jobs:
  verify-new-tokens:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Run verify tokens script
        run: yarn verify